#+TITLE: 实验物理的大数据方法课程大纲

从20世纪60年代大科学仪器时代开始，大型物理和天文学实验一直是大数据发展的驱动力。近年来，大数据方法在各学科和工业界的广泛应用和发展，又为实验物理的大规模数据处理提供了新了方法和技术。

本课程系列以实验物理和大数据方法为结合点，以粒子与核物理、天体物理、辐射成像、凝聚态物理中数据处理的真实场景为背景，带领同学进行 Unix 类工具支撑的 Python 大规模科学计算，构建从原始数据到论文图表的端对端数据流水线，通过适合的任务来驱动学习具体的数据处理技能。

* 课前准备
** 盲打练习
   达到每分钟 25 词以上。
** 环境准备
   Windows 用户启动 WSL 并安装 Debian Bullseye 及以上，配置图形界面

   MacOS 用户，安装 GNU 环境
** 编辑器
   学习使用程序编辑器

* Python 数据处理
  重点：Git、迭代器、生成器、多维数组
** 课程简介与版本控制
   课程目标、课程体系、数据分析四项原则、提问的智慧、GNU 环境配置、SSH 通信。
   + POSIX 的两大流派 BSD / GNU
   + 加入逻辑电路的起源、通用电子计算机的发明、MANIAC 氢单与蒙特卡罗
   + 抄袭的定义
** Git 基本操作与Python 入门
   - Git
     modified staged committed 三种状态、Commit message 写法
   - Python
     特点与应用、算术运算、基本数据类型、变量、阅读错误提示、脚本
** 程序结构、函数与复合数据结构
   顺序、选择、循环结构，语句体与缩进，for 循环与迭代器
   - 函数
     map、lambda、名字空间
   - 复合数据结构
     列表、元组、字典、defaultdict、Counter
** 文件输入输出、调试与生成器
   - 读取和写入文件
   - 程序调试
     breakpoint() ， python debugger （pdb）环境
   - 代码风格与测试
   - 高级索引
     迭代器与生成器
   - 迭代器
     乘积、组合、排列、zip、过滤器、slice
** 迭代器标准库
   - NumPy 数组
     数组生成、叠放、矩阵运算
   - NumPy 张量运算
     tensordot、einsum
   - 复合数据数组
     structured array
   - SciPy 模块使用
     integrate
** 数据格式
   CSV、HDF5、JSON 各自的特点，输入输出，查看器
** 大作业
   - 黑白棋娱乐讨论
** 数据可视化
   Matplotlib 散点图、直方图、着色图、格点、Grammer of Graphics   

* 命令行
** 命令行入门
   - 数据生产线的基本概念
   - 学习目的
     满足数据处理四原则、胶水功能、自动性、普适性
   - shell 外壳命令的类型
     二进制程序、脚本、内建命令、函数、别名
   - 管道
     标准输入输出，重定向
   - 常用命令
     ls、echo、cat、wc、seq、grep、paste、awk、bc、tr、
     hostname、uname、id、date、uptime、find、touch、file、
     sort、uniq、tail

   - 娱乐命令
     sl、cacafire、bb、cmatrix、cowsay

   - 提高命令
     sha256sum、nc、mkfifo、mktemp
   - 通配符

** GNU Make
   数据生产线的实现、理解 Make 是管理流程的最佳工具、机器与人皆可读文档
   - 流程单元：Makefile 的基本组成
     输入数据、输出数据、程序执行
   - Makefile 的基本格式
     特别变量：$^、$@、$$
   - Make 的程序特性
     变量、%、函数
   - 特殊目标
     .SECONDARY、.PHONY、.DELETE_ON_ERROR
** 正则表达式
   数学模型、语法要素、字符集
   - sed、grep
   - bash 中的正则表达式
   - 聚合命令
     xargs
   - 进程控制
     Ctrl-C、Ctrl-Z、bg、fg、jobs

** bash shell 脚本
   - shell 脚本
     参数传递、变量、函数、引用、算术运算、程序结构
   - shell 程序返回值
     0 代表成功，非 0 代表失败 "$?"
* 关系代数
** 科学范式与关系代数
   经验、理论、计算、数据
   - 知道的量化程度
     0 类、1 类、A 类、Z 类
   - 数据组织
     关系代数的组织形式与发展历史
   - 关系代数
     表格的普适性、集合运算、线性运算、关系运算、GroupBy
   - 关系代数的表现
     SQL、DataFrame
   - SQL 语言
     CREATE、INSERT、SELECT、UNION、EXCEPT、INTERSECT、WHERE、JOIN、DROP
   - SQLite3 环境
     命令行 REPL、Python 模块
** SQL 数据处理实例
   - CASE...WHEN...END
   - 函数：avg()
   - 引用
   - SQL 描述型语言与步骤型程序的风格区别
   - Makefile 统合
** 关系代数的DataFrame实现
   - Pandas
     csv 与 SQLite 的输入输出、merge()、groupby()
   - R
   - 基于多因素的绘图
** 回归分析
   - 常用工具
     statsmodels、sklearn
   - 拟合方法
     绘制关系图，找出重要的自变量，逐级添加自变量，多元广义线性回归，连续与离散自变量
   - 拟合结果的统计解读
     残差图、回归预测图
   - pasty 的 R 风格一般型回归公式
   - 广义线性回归
     泊松回归、二项回归
