#+TITLE: 实验物理的大数据方法课程大纲

从20世纪60年代大科学仪器时代开始，大型物理和天文学实验一直是大数据发展的驱动力。近年来，大数据方法在各学科和工业界的广泛应用和发展，又为实验物理的大规模数据处理提供了新了方法和技术。

本课程系列以实验物理和大数据方法为结合点，以粒子与核物理、天体物理、辐射成像、凝聚态物理中数据处理的真实场景为背景，带领同学进行 Unix 类工具支撑的 Python 大规模科学计算，构建从原始数据到论文图表的端对端数据流水线，通过适合的任务来驱动学习具体的数据处理技能。

* 课前准备
** 盲打练习
   达到每分钟 25 词以上。
** 环境准备
   Windows 用户启动 WSL 并安装 Debian Bullseye 及以上，配置图形界面
** 编辑器
   学习使用程序编辑器

* Python 数据处理
** 课程简介与版本控制
   课程目标、课程体系、数据分析四项原则、提问的智慧、POSIX 环境配置、SSH 通信。
   + 加入逻辑电路的起源、通用电子计算机的发明、MANIAC 氢单与蒙特卡罗
   + 抄袭的定义
** Git 基本操作与Python 入门
   - Git
     modified staged committed 三种状态、Commit message 写法
   - Python
     特点与应用、算术运算、基本数据类型、变量、阅读错误提示、脚本
** 程序结构、函数与复合数据结构
   顺序、选择、循环结构，语句体与缩进，for 循环与迭代器
   - 函数
     map、lambda、名字空间
   - 复合数据结构
     列表、元组、字典、defaultdict、Counter
** 文件输入输出、调试与生成器
   - 读取和写入文件
   - 程序调试
     breakpoint() ， python debugger （pdb）环境
   - 代码风格与测试
   - 高级索引
     迭代器与生成器
   - 迭代器
     乘积、组合、排列、zip、过滤器、slice
** 迭代器标准库
   - NumPy 数组
     数组生成、叠放、矩阵运算
   - NumPy 张量运算
     tensordot、einsum
   - 复合数据数组
     structured array
   - SciPy 模块使用
     integrate
** 数据格式
   CSV、HDF5、JSON 各自的特点，输入输出，查看器
