#+TITLE: Python 脚本
#+author: 续本达
#+PROPERTY: header-args :eval never-export :exports both

* 文件读取
  文本文件输入输出，可使用 =open()= 。用 for 循环可将打开的文件视为迭代器逐行读入。每次循环得到字符串可进一步处理。在 Python 当前文件夹的命令行中，下载一个文本文件样例，
  
  #+NAME: 43815ce6-6cab-4090-a0c8-55c19ac6d1e6
  #+begin_src ein-bash :results output :session https://dpcg.g.airelinux.org/user/xubd/lecture.ipynb
    wget --progress=dot 'http://hep.tsinghua.edu.cn/~orv/pd/iterator.txt'
  #+end_src

  #+RESULTS: 43815ce6-6cab-4090-a0c8-55c19ac6d1e6
  #+begin_example
  --2022-07-07 10:22:24--  http://hep.tsinghua.edu.cn/~orv/pd/iterator.txt
  Resolving hep.tsinghua.edu.cn... 101.6.6.219, 2402:f000:1:416:101:6:6:219
  Connecting to hep.tsinghua.edu.cn|101.6.6.219|:80... connected.
  HTTP request sent, awaiting response... 200 OK
  Length: 268 [text/plain]
  Saving to: ‘iterator.txt’

       0K                                                       100% 37.3M=0s

  2022-07-07 10:22:24 (37.3 MB/s) - ‘iterator.txt’ saved [268/268]

  #+end_example

  使用 open() 读入，用迭代器逐行读取。
  
  #+NAME: e0c90143-dcb5-4c16-a87e-d2c4d779ab32
  #+begin_src ein-python :results output :session https://dpcg.g.airelinux.org/user/xubd/lecture-python.ipynb
    for l in open("iterator.txt"):
        print(l, end="")
  #+end_src

  #+RESULTS: e0c90143-dcb5-4c16-a87e-d2c4d779ab32
  : Iterator Types
  : 
  : Python supports a concept of iteration over containers. This is
  : implemented using two distinct methods; these are used to allow
  : user-defined classes to support iteration. Sequences, described below
  : in more detail, always support the iteration methods.

  读入的字符串带有换行符，与 =print= 叠加会有空行，因此给 =print= 传了 =end= 参数。

  写入文本文件时，令 =open()= 以写模式打开。
  #+NAME: ed8b5ee6-5276-4e67-82f8-71d64eaac126
  #+begin_src ein-python :results output :session https://dpcg.g.airelinux.org/user/xubd/lecture-python.ipynb
    f = open("log.txt", 'w')
    f.write("第一天 概论\n")
    f.write("第二天 Python 入门\n")
    f.close()
  #+end_src

  #+RESULTS: ed8b5ee6-5276-4e67-82f8-71d64eaac126
  "\n" 是换行符。在命令行中查看输出的文件，
  #+NAME: deace4df-afc7-45b4-8f03-9ae249f9ebf5
  #+begin_src ein-bash :results output :session https://dpcg.g.airelinux.org/user/xubd/lecture.ipynb
    cat log.txt
  #+end_src

  #+RESULTS: deace4df-afc7-45b4-8f03-9ae249f9ebf5
  : 第一天 概论
  : 第二天 Python 入门

  有了输入输出的方法，我们可以把 Python 的字符串处理功能与程序结构、复合数据结构等结合起来，完成实用的文本处理工作。
